-- Update users table to include all necessary fields
ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS full_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS school_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS student_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS contact_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS program VARCHAR(255),
ADD COLUMN IF NOT EXISTS department VARCHAR(255); 